name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Use environment variable and secret
        env:
          MY_ENV_VAR: ${{ env.WORKFLOW.DOCKER_USERNAME }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "My environment variable is $MY_ENV_VAR"
          echo "My secret is $MY_SECRET"  
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.WORKFLOW.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
